import { Listing } from "./types";

export const LISTINGS: Listing[] = [
  {
    id: "1",
    title: "Luxury Villa with Infinity Pool",
    location: "Bali, Indonesia",
    distance: "9,832 km away",
    dates: "Oct 22 - 27",
    price: 350,
    rating: 4.98,
    images: [
      "https://picsum.photos/id/10/800/600",
      "https://picsum.photos/id/11/800/600",
      "https://picsum.photos/id/12/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: -8.409518,
    lng: 115.188919,
    description:
      "Experience the ultimate tropical getaway in this stunning villa featuring a private infinity pool overlooking the lush jungle.",
    host: {
      name: "Wayan",
      image: "https://picsum.photos/id/64/100/100",
      superhost: true,
    },
  },
  {
    id: "2",
    title: "Cozy Alpine A-Frame",
    location: "Dolomites, Italy",
    distance: "4,200 km away",
    dates: "Nov 5 - 12",
    price: 185,
    rating: 4.95,
    images: [
      "https://picsum.photos/id/28/800/600",
      "https://picsum.photos/id/29/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: 46.4102,
    lng: 11.8441,
    description:
      "A perfect retreat for hikers and skiers. Enjoy the fireplace after a long day in the mountains.",
    host: {
      name: "Matteo",
      image: "https://picsum.photos/id/65/100/100",
      superhost: false,
    },
  },
  {
    id: "3",
    title: "Modern Beachfront Condo",
    location: "Miami, Florida",
    distance: "1,500 km away",
    dates: "Dec 10 - 17",
    price: 420,
    rating: 4.85,
    images: [
      "https://picsum.photos/id/35/800/600",
      "https://picsum.photos/id/36/800/600",
    ],
    category: "imoveis",
    type: "apartamento",
    finalidade: "aluguer",
    lat: 25.7617,
    lng: -80.1918,
    description:
      "Wake up to the sound of waves. Direct beach access and minutes away from the best nightlife.",
    host: {
      name: "Sarah",
      image: "https://picsum.photos/id/66/100/100",
      superhost: true,
    },
  },
  {
    id: "4",
    title: "Unique UFO House",
    location: "Joshua Tree, CA",
    distance: "200 km away",
    dates: "Jan 15 - 20",
    price: 299,
    rating: 4.99,
    images: [
      "https://picsum.photos/id/40/800/600",
      "https://picsum.photos/id/41/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: 34.1347,
    lng: -116.3131,
    description:
      "Out of this world! Stay in a fully restored Futuro house in the middle of the desert.",
    host: {
      name: "Zorg",
      image: "https://picsum.photos/id/67/100/100",
      superhost: true,
    },
  },
  {
    id: "5",
    title: "Secluded Forest Yurt",
    location: "Portland, Oregon",
    distance: "800 km away",
    dates: "Mar 3 - 8",
    price: 120,
    rating: 4.91,
    images: [
      "https://picsum.photos/id/50/800/600",
      "https://picsum.photos/id/51/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: 45.5152,
    lng: -122.6784,
    description:
      "Glamping at its finest. Heated floors, skylight, and complete silence in the woods.",
    host: {
      name: "River",
      image: "https://picsum.photos/id/68/100/100",
      superhost: false,
    },
  },
  {
    id: "6",
    title: "Architectural Masterpiece",
    location: "Copenhagen, Denmark",
    distance: "5,500 km away",
    dates: "Apr 12 - 19",
    price: 550,
    rating: 5.0,
    images: [
      "https://picsum.photos/id/60/800/600",
      "https://picsum.photos/id/61/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: 55.6761,
    lng: 12.5683,
    description:
      "Stay in an award-winning home featured in multiple design magazines.",
    host: {
      name: "Lars",
      image: "https://picsum.photos/id/69/100/100",
      superhost: true,
    },
  },
  {
    id: "7",
    title: "Ocean View Penthouse",
    location: "Cape Town, South Africa",
    distance: "12,000 km away",
    dates: "May 1 - 7",
    price: 310,
    rating: 4.88,
    images: [
      "https://picsum.photos/id/70/800/600",
      "https://picsum.photos/id/71/800/600",
    ],
    category: "imoveis",
    type: "apartamento",
    finalidade: "aluguer",
    lat: -33.9249,
    lng: 18.4241,
    description:
      "Stunning views of Table Mountain and the ocean. Private rooftop pool.",
    host: {
      name: "Amara",
      image: "https://picsum.photos/id/72/100/100",
      superhost: true,
    },
  },
  {
    id: "8",
    title: "Historic Castle Suite",
    location: "Edinburgh, Scotland",
    distance: "5,200 km away",
    dates: "Jun 10 - 15",
    price: 450,
    rating: 4.96,
    images: [
      "https://picsum.photos/id/80/800/600",
      "https://picsum.photos/id/81/800/600",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: 55.9533,
    lng: -3.1883,
    description:
      "Live like royalty in this 16th-century castle wing. Includes private tour.",
    host: {
      name: "Hamish",
      image: "https://picsum.photos/id/73/100/100",
      superhost: true,
    },
  },
  // Imóveis adicionais (foco Moçambique)
  {
    id: "9",
    title: "Casa T3 com quintal em Maputo",
    location: "Bairro da Coop, Maputo",
    distance: "Próximo ao centro",
    dates: "Disponível este mês",
    price: 90,
    rating: 4.7,
    images: [
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      "https://images.pexels.com/photos/259580/pexels-photo-259580.jpeg",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: -25.9667,
    lng: 32.5833,
    description:
      "Casa T3 murada, com quintal amplo, ideal para famílias em Maputo. Próxima de transportes e escolas.",
    host: {
      name: "Helena",
      image: "https://images.pexels.com/photos/3760854/pexels-photo-3760854.jpeg",
      superhost: true,
    },
  },
  {
    id: "10",
    title: "Apartamento moderno na Polana",
    location: "Polana, Maputo",
    distance: "Vista para a baía",
    dates: "Disponível todo o ano",
    price: 110,
    rating: 4.8,
    images: [
      "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg",
    ],
    category: "imoveis",
    type: "apartamento",
    finalidade: "aluguer",
    lat: -25.9661,
    lng: 32.5965,
    description:
      "Apartamento T2 com varanda e vista mar, internet rápida e garagem. Perfeito para estadias de negócios.",
    host: {
      name: "Rui",
      image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
      superhost: false,
    },
  },
  {
    id: "11",
    title: "Quarto mobilado para estudante",
    location: "Matola, Maputo",
    distance: "15 minutos da cidade",
    dates: "A partir de Março",
    price: 45,
    rating: 4.5,
    images: [
      "https://images.pexels.com/photos/1454804/pexels-photo-1454804.jpeg",
      "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    ],
    category: "imoveis",
    type: "quarto",
    finalidade: "aluguer",
    lat: -25.9622,
    lng: 32.4589,
    description:
      "Quarto individual com cama, roupeiro e secretária. Ambiente calmo, ideal para estudantes.",
    host: {
      name: "Carlos",
      image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
      superhost: false,
    },
  },
  {
    id: "12",
    title: "Vivenda em condomínio fechado",
    location: "Matola Rio, Maputo",
    distance: "Acesso fácil à EN4",
    dates: "Fins de semana e feriados",
    price: 130,
    rating: 4.9,
    images: [
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
      "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
    ],
    category: "imoveis",
    type: "casa",
    finalidade: "aluguer",
    lat: -25.995,
    lng: 32.45,
    description:
      "Vivenda espaçosa com jardim e zona de braai, ideal para famílias e eventos pequenos.",
    host: {
      name: "Quinta Rio",
      image: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
      superhost: true,
    },
  },
  // Logística
  {
    id: "13",
    title: "Camião 7T para mudanças",
    location: "Maputo e arredores",
    distance: "Cobertura regional",
    dates: "Reserva por dia",
    price: 150,
    rating: 4.9,
    images: [
      "https://images.pexels.com/photos/6169052/pexels-photo-6169052.jpeg",
      "https://images.pexels.com/photos/6169055/pexels-photo-6169055.jpeg",
    ],
    category: "logistica",
    type: "mudanças",
    lat: -25.95,
    lng: 32.6,
    description:
      "Camião fechado de 7 toneladas com equipa para carregamento e descarga. Ideal para mudanças completas.",
    host: {
      name: "Transporte Maputo",
      image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
      superhost: true,
    },
  },
  {
    id: "14",
    title: "Serviço de mudanças leve",
    location: "Cidade de Maputo",
    distance: "Cobertura urbana",
    dates: "Todos os dias da semana",
    price: 80,
    rating: 4.6,
    images: [
      "https://images.pexels.com/photos/7464709/pexels-photo-7464709.jpeg",
      "https://images.pexels.com/photos/5025669/pexels-photo-5025669.jpeg",
    ],
    category: "logistica",
    type: "mudanças",
    lat: -25.97,
    lng: 32.58,
    description:
      "Carrinha fechada para pequenas mudanças e entregas de móveis e eletrodomésticos.",
    host: {
      name: "Logística Rápida",
      image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg",
      superhost: false,
    },
  },
  {
    id: "15",
    title: "Transporte de carga refrigerada",
    location: "Maputo · Beira · Nampula",
    distance: "Várias províncias",
    dates: "Por orçamento",
    price: 260,
    rating: 4.7,
    images: [
      "https://images.pexels.com/photos/6169043/pexels-photo-6169043.jpeg",
      "https://images.pexels.com/photos/6169044/pexels-photo-6169044.jpeg",
    ],
    category: "logistica",
    type: "carga",
    lat: -25.96,
    lng: 32.58,
    description:
      "Serviço de transporte de produtos frescos com camiões refrigerados, ideal para negócios alimentares.",
    host: {
      name: "FreshCargo",
      image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
      superhost: true,
    },
  },
  {
    id: "16",
    title: "Aluguer de camião basculante",
    location: "Zona industrial de Maputo",
    distance: "Serviços pontuais",
    dates: "Seg–Sáb",
    price: 190,
    rating: 4.4,
    images: [
      "https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg",
      "https://images.pexels.com/photos/2199294/pexels-photo-2199294.jpeg",
    ],
    category: "logistica",
    type: "camiões",
    lat: -25.96,
    lng: 32.55,
    description:
      "Camião basculante para obras e transporte de areia, pedra e entulho.",
    host: {
      name: "ConstruLog",
      image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg",
      superhost: false,
    },
  },
  // Eventos
  {
    id: "17",
    title: "Salão para casamentos até 300 pessoas",
    location: "Matola Rio, Maputo",
    distance: "Acesso pela EN4",
    dates: "Fins de semana e feriados",
    price: 400,
    rating: 4.9,
    images: [
      "https://images.pexels.com/photos/169211/pexels-photo-169211.jpeg",
      "https://images.pexels.com/photos/1857157/pexels-photo-1857157.jpeg",
    ],
    category: "eventos",
    type: "salões",
    lat: -25.99,
    lng: 32.47,
    description:
      "Salão amplo com estacionamento e espaço exterior para fotografias. Ideal para casamentos grandes.",
    host: {
      name: "Quinta Azul",
      image: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
      superhost: true,
    },
  },
  {
    id: "18",
    title: "Espaço para workshops e formações",
    location: "Centro da Beira",
    distance: "Próximo a serviços",
    dates: "Seg–Sáb",
    price: 120,
    rating: 4.5,
    images: [
      "https://images.pexels.com/photos/1181395/pexels-photo-1181395.jpeg",
      "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg",
    ],
    category: "eventos",
    type: "workshops",
    lat: -19.8436,
    lng: 34.8389,
    description:
      "Sala climatizada com projetor e internet, ideal para formações, reuniões e pequenos eventos corporativos.",
    host: {
      name: "Centro Negócios Beira",
      image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg",
      superhost: false,
    },
  },
  {
    id: "19",
    title: "Quinta para eventos ao ar livre",
    location: "Boane, Maputo",
    distance: "Área verde ampla",
    dates: "Por marcação",
    price: 350,
    rating: 4.8,
    images: [
      "https://images.pexels.com/photos/169211/pexels-photo-169211.jpeg",
      "https://images.pexels.com/photos/1857157/pexels-photo-1857157.jpeg",
    ],
    category: "eventos",
    type: "quintas",
    lat: -26.04,
    lng: 32.35,
    description:
      "Quinta com jardins, piscina e tenda para festas. Ideal para casamentos, festas privadas e eventos corporativos.",
    host: {
      name: "Quinta Verde",
      image: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
      superhost: true,
    },
  },
  {
    id: "20",
    title: "Espaço para conferências",
    location: "Baixa de Maputo",
    distance: "Zona empresarial",
    dates: "Durante a semana",
    price: 180,
    rating: 4.4,
    images: [
      "https://images.pexels.com/photos/1181395/pexels-photo-1181395.jpeg",
      "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg",
    ],
    category: "eventos",
    type: "workshops",
    lat: -25.9692,
    lng: 32.5732,
    description:
      "Auditório equipado com som, projeção e cadeiras confortáveis, pronto para conferências e lançamentos.",
    host: {
      name: "Maputo Business Center",
      image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
      superhost: false,
    },
  },
];
